name: Build APK using Buildozer

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y zip unzip openjdk-17-jdk python3-pip
        pip install buildozer cython
        yes | sdkmanager --licenses || true
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: scientific-calculator-apk
        path: bin/*.apk
        
